import { useState, useEffect } from 'react'

function App() {
  const [status, setStatus] = useState('loading...')

  useEffect(() => {
    fetch('/api/health')
      .then(res => res.json())
      .then(data => setStatus(data.status))
      .catch(() => setStatus('Backend not running'))
  }, [])

  return (
    <div className="app">
      <header>
        <h1>my_project</h1>
        <p>Generated by VibeCober</p>
      </header>
      <main>
        <div className="status-card">
          <h2>Backend Status</h2>
          <p className={status === 'healthy' ? 'status-ok' : 'status-error'}>
            {status}
          </p>
        </div>
        <div className="modules">
          <h2>Modules</h2>
          <ul>
            <li>task creation</li>
            <li>task assignment</li>
            <li>task tracking</li>
            <li>due date management</li>
            <li>notifications</li>
          </ul>
        </div>
      </main>
    </div>
  )
}

export default App
