"""
Test Agent - Generates pytest test suite

Input: Auth agent output, DB schema
Output: pytest tests for auth + health endpoints

Deterministic. Real tests. No mocks.
"""

from typing import Dict, Any, List
from pydantic import BaseModel


# ========== TYPES ==========

class SuiteOutput(BaseModel):
    """Pydantic model for test suite output (name avoids pytest collection)."""
    framework: str = "pytest"
    tests: List[str]
    requires_test_db: bool = True
    files: Dict[str, str]


# ========== TEST TEMPLATES ==========

CONFTEST_TEMPLATE = '''"""
Pytest fixtures - Test database and client setup
Auto-generated by VibeCober Test Agent
"""

import pytest
from fastapi.testclient import TestClient
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.pool import StaticPool

# Import your app and models
from main import app
from database import Base, get_db


# Test database - in-memory SQLite
SQLALCHEMY_TEST_DATABASE_URL = "sqlite:///:memory:"

engine = create_engine(
    SQLALCHEMY_TEST_DATABASE_URL,
    connect_args={"check_same_thread": False},
    poolclass=StaticPool,
)
TestingSessionLocal = sessionmaker(autocommit=False, autoflush=False, bind=engine)


def override_get_db():
    """Override database dependency for tests"""
    db = TestingSessionLocal()
    try:
        yield db
    finally:
        db.close()


@pytest.fixture(scope="function")
def db():
    """Create fresh database for each test"""
    Base.metadata.create_all(bind=engine)
    db = TestingSessionLocal()
    yield db
    db.close()
    Base.metadata.drop_all(bind=engine)


@pytest.fixture(scope="function")
def client(db):
    """Test client with database override"""
    app.dependency_overrides[get_db] = override_get_db
    Base.metadata.create_all(bind=engine)
    
    with TestClient(app) as c:
        yield c
    
    Base.metadata.drop_all(bind=engine)
    app.dependency_overrides.clear()


@pytest.fixture
def test_user_data():
    """Sample user data for tests"""
    return {
        "email": "test@example.com",
        "password": "testpassword123",
        "name": "Test User"
    }


@pytest.fixture
def registered_user(client, test_user_data):
    """Create a registered user and return data with token"""
    # Register
    response = client.post("/auth/register", json=test_user_data)
    assert response.status_code == 201
    
    # Login to get token
    login_response = client.post("/auth/login", json={
        "email": test_user_data["email"],
        "password": test_user_data["password"]
    })
    assert login_response.status_code == 200
    
    token = login_response.json()["access_token"]
    
    return {
        **test_user_data,
        "token": token,
        "headers": {"Authorization": f"Bearer {token}"}
    }
'''


TEST_AUTH_TEMPLATE = '''"""
Auth endpoint tests - Register, Login, Profile
Auto-generated by VibeCober Test Agent
"""

import pytest


class TestRegister:
    """Tests for POST /auth/register"""
    
    def test_register_success(self, client, test_user_data):
        """Test successful user registration"""
        response = client.post("/auth/register", json=test_user_data)
        
        assert response.status_code == 201
        data = response.json()
        assert data["email"] == test_user_data["email"]
        assert data["name"] == test_user_data["name"]
        assert "id" in data
        assert "password" not in data  # Password should not be returned
    
    def test_register_duplicate_email(self, client, test_user_data):
        """Test registration with existing email fails"""
        # First registration
        client.post("/auth/register", json=test_user_data)
        
        # Duplicate registration
        response = client.post("/auth/register", json=test_user_data)
        
        assert response.status_code == 400
        assert "already registered" in response.json()["detail"].lower()
    
    def test_register_invalid_email(self, client):
        """Test registration with invalid email fails"""
        response = client.post("/auth/register", json={
            "email": "not-an-email",
            "password": "password123",
            "name": "Test"
        })
        
        assert response.status_code == 422  # Validation error


class TestLogin:
    """Tests for POST /auth/login"""
    
    def test_login_success(self, client, test_user_data):
        """Test successful login returns token"""
        # Register first
        client.post("/auth/register", json=test_user_data)
        
        # Login
        response = client.post("/auth/login", json={
            "email": test_user_data["email"],
            "password": test_user_data["password"]
        })
        
        assert response.status_code == 200
        data = response.json()
        assert "access_token" in data
        assert data["token_type"] == "bearer"
    
    def test_login_wrong_password(self, client, test_user_data):
        """Test login with wrong password fails"""
        # Register
        client.post("/auth/register", json=test_user_data)
        
        # Login with wrong password
        response = client.post("/auth/login", json={
            "email": test_user_data["email"],
            "password": "wrongpassword"
        })
        
        assert response.status_code == 401
    
    def test_login_nonexistent_user(self, client):
        """Test login with non-existent user fails"""
        response = client.post("/auth/login", json={
            "email": "nobody@example.com",
            "password": "password123"
        })
        
        assert response.status_code == 401


class TestMe:
    """Tests for GET /auth/me"""
    
    def test_me_success(self, client, registered_user):
        """Test getting current user profile"""
        response = client.get("/auth/me", headers=registered_user["headers"])
        
        assert response.status_code == 200
        data = response.json()
        assert data["email"] == registered_user["email"]
        assert data["name"] == registered_user["name"]
    
    def test_me_no_token(self, client):
        """Test accessing /me without token fails"""
        response = client.get("/auth/me")
        
        assert response.status_code == 403  # No credentials
    
    def test_me_invalid_token(self, client):
        """Test accessing /me with invalid token fails"""
        response = client.get("/auth/me", headers={
            "Authorization": "Bearer invalid-token"
        })
        
        assert response.status_code == 401
'''


TEST_HEALTH_TEMPLATE = '''"""
Health check tests
Auto-generated by VibeCober Test Agent
"""


class TestHealth:
    """Tests for health endpoints"""
    
    def test_health_check(self, client):
        """Test health endpoint returns healthy status"""
        response = client.get("/health")
        
        assert response.status_code == 200
        assert response.json()["status"] == "healthy"
    
    def test_root_endpoint(self, client):
        """Test root endpoint returns API info"""
        response = client.get("/")
        
        assert response.status_code == 200
        data = response.json()
        assert "status" in data or "version" in data
'''


PYTEST_INI_TEMPLATE = '''[pytest]
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = -v --tb=short
'''


# ========== TEST AGENT ==========

class SuiteGenerator:
    """
    Generates pytest test suite based on auth and db schema.
    Deterministic template-based generation. (Name avoids pytest collection.)
    """
    
    def __init__(self, auth_output: Dict[str, Any], db_schema: Dict[str, Any]):
        self.auth_output = auth_output
        self.db_schema = db_schema
        self.has_auth = bool(auth_output.get("auth", {}).get("routes", []))
    
    def generate(self) -> SuiteOutput:
        """Generate complete test suite"""
        files = {}
        tests = []
        
        # Always generate conftest
        files["tests/conftest.py"] = CONFTEST_TEMPLATE.strip()
        files["tests/__init__.py"] = '"""Test package"""'
        files["pytest.ini"] = PYTEST_INI_TEMPLATE.strip()
        
        # Health tests - always included
        files["tests/test_health.py"] = TEST_HEALTH_TEMPLATE.strip()
        tests.append("health")
        
        # Auth tests - if auth was generated
        if self.has_auth:
            files["tests/test_auth.py"] = TEST_AUTH_TEMPLATE.strip()
            tests.append("auth")
        
        return SuiteOutput(
            framework="pytest",
            tests=tests,
            requires_test_db=True,
            files=files
        )


# ========== PUBLIC API ==========

def run_test_agent(context: Dict[str, Any]) -> Dict[str, Any]:
    """
    Main entry point for orchestrator. (Named to avoid pytest collection.)
    
    Args:
        context: Should contain 'auth' and 'db_schema' outputs
        
    Returns:
        Dict with test config and generated files
    """
    auth_output = context.get("auth", {})
    db_schema = context.get("db_schema", {})
    
    agent = SuiteGenerator(auth_output, db_schema)
    output = agent.generate()
    
    return {
        "tests": output.model_dump(),
        "test_count": len(output.tests),
        "files_count": len(output.files),
        "status": "success"
    }


# ========== EXAMPLE USAGE ==========

if __name__ == "__main__":
    # Test with sample outputs
    sample_auth = {
        "auth": {
            "strategy": "jwt",
            "routes": ["register", "login", "me"]
        }
    }
    sample_db = {
        "schema": {"tables": [{"name": "users"}]}
    }
    
    result = run_test_agent({"auth": sample_auth, "db_schema": sample_db})
    
    print("=" * 60)
    print("TEST OUTPUT:")
    print("=" * 60)
    print(f"Framework: {result['tests']['framework']}")
    print(f"Tests: {result['tests']['tests']}")
    print(f"Files: {list(result['tests']['files'].keys())}")
    
    print("\n" + "=" * 60)
    print("TEST_AUTH.PY (first 500 chars):")
    print("=" * 60)
    print(result['tests']['files']['tests/test_auth.py'][:500])
