"""
Code Templates - Real working starter code for generated projects
"""

BACKEND_MAIN = '''from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI(
    title="{project_name}",
    description="Generated by VibeCober",
    version="1.0.0"
)

# CORS for frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000", "http://localhost:5173"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/")
def root():
    return {{"status": "running", "app": "{project_name}"}}

@app.get("/api/health")
def health_check():
    return {{"status": "healthy"}}

# TODO: Add your routes here
'''

BACKEND_REQUIREMENTS = '''fastapi==0.109.0
uvicorn==0.27.0
pydantic==2.5.3
python-dotenv==1.0.0
'''

BACKEND_ENV = '''# Environment Variables
DEBUG=True
DATABASE_URL=postgresql://user:password@localhost:5432/{project_name}
SECRET_KEY=your-secret-key-here
'''

FRONTEND_PACKAGE_JSON = '''{{
  "name": "{project_name}-frontend",
  "private": true,
  "version": "0.1.0",
  "type": "module",
  "scripts": {{
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  }},
  "dependencies": {{
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  }},
  "devDependencies": {{
    "@vitejs/plugin-react": "^4.2.1",
    "vite": "^5.0.12"
  }}
}}
'''

FRONTEND_VITE_CONFIG = '''import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
  plugins: [react()],
  server: {
    port: 3000,
    proxy: {
      '/api': 'http://localhost:8000'
    }
  }
})
'''

FRONTEND_INDEX_HTML = '''<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{project_name}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.jsx"></script>
  </body>
</html>
'''

FRONTEND_MAIN_JSX = '''import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
import './index.css'

ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
)
'''

FRONTEND_APP_JSX = '''import {{ useState, useEffect }} from 'react'

function App() {{
  const [status, setStatus] = useState('loading...')

  useEffect(() => {{
    fetch('/api/health')
      .then(res => res.json())
      .then(data => setStatus(data.status))
      .catch(() => setStatus('Backend not running'))
  }}, [])

  return (
    <div className="app">
      <header>
        <h1>{project_name}</h1>
        <p>Generated by VibeCober</p>
      </header>
      <main>
        <div className="status-card">
          <h2>Backend Status</h2>
          <p className={{status === 'healthy' ? 'status-ok' : 'status-error'}}>
            {{status}}
          </p>
        </div>
        <div className="modules">
          <h2>Modules</h2>
          <ul>
            {modules_list}
          </ul>
        </div>
      </main>
    </div>
  )
}}

export default App
'''

FRONTEND_CSS = '''* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
  background: linear-gradient(135deg, #1a1a2e 0%, #16213e 100%);
  min-height: 100vh;
  color: #fff;
}

.app {
  max-width: 800px;
  margin: 0 auto;
  padding: 2rem;
}

header {
  text-align: center;
  margin-bottom: 3rem;
}

header h1 {
  font-size: 2.5rem;
  background: linear-gradient(90deg, #00d9ff, #00ff88);
  -webkit-background-clip: text;
  -webkit-text-fill-color: transparent;
  margin-bottom: 0.5rem;
}

header p {
  color: #888;
}

.status-card {
  background: rgba(255,255,255,0.05);
  border-radius: 12px;
  padding: 1.5rem;
  margin-bottom: 2rem;
  border: 1px solid rgba(255,255,255,0.1);
}

.status-card h2 {
  font-size: 1rem;
  color: #888;
  margin-bottom: 0.5rem;
}

.status-ok {
  color: #00ff88;
  font-size: 1.5rem;
  font-weight: bold;
}

.status-error {
  color: #ff4444;
  font-size: 1.5rem;
}

.modules {
  background: rgba(255,255,255,0.05);
  border-radius: 12px;
  padding: 1.5rem;
  border: 1px solid rgba(255,255,255,0.1);
}

.modules h2 {
  font-size: 1rem;
  color: #888;
  margin-bottom: 1rem;
}

.modules ul {
  list-style: none;
}

.modules li {
  padding: 0.75rem 1rem;
  background: rgba(0,217,255,0.1);
  border-radius: 8px;
  margin-bottom: 0.5rem;
  border-left: 3px solid #00d9ff;
}
'''

README_TEMPLATE = '''# {project_name}

> Generated by VibeCober

## Architecture

- **Backend**: {backend}
- **Frontend**: {frontend}
- **Database**: {database}

## Modules

{modules_md}

## Quick Start

### Backend
```bash
cd backend
pip install -r requirements.txt
uvicorn main:app --reload
```

### Frontend
```bash
cd frontend
npm install
npm run dev
```

## API Endpoints

- `GET /` - Root status
- `GET /api/health` - Health check

---
Built with VibeCober
'''


def get_templates(project_name: str, architecture: dict) -> dict:
    """Generate all templates with project-specific values.
    
    Now tech-aware: detects the stack from architecture and generates
    appropriate templates instead of always defaulting to React + FastAPI.
    """
    from backend.core.tech_detector import detect_stack
    
    modules = architecture.get('modules', ['core'])
    modules_list = '\n            '.join([f'<li>{m}</li>' for m in modules])
    modules_md = '\n'.join([f'- {m}' for m in modules])
    
    backend_fw = architecture.get('backend', '')
    frontend_fw = architecture.get('frontend', '')
    
    # Detect stack from architecture hints
    stack_hint = f"{backend_fw} {frontend_fw} {architecture.get('database', '')}"
    detected = detect_stack(stack_hint)
    
    # Build appropriate project structure based on detected stack
    project = {}
    
    # --- Backend ---
    if backend_fw and backend_fw.lower() != "none":
        bl = detected.backend_language or "python"
        
        if bl == "python":
            project["backend"] = {
                "main.py": BACKEND_MAIN.format(project_name=project_name),
                "requirements.txt": BACKEND_REQUIREMENTS,
                ".env.example": BACKEND_ENV.format(project_name=project_name),
            }
        elif bl in ("javascript", "typescript"):
            ext = ".ts" if bl == "typescript" else ".js"
            project["backend"] = {
                "package.json": f'{{"name": "{project_name}-backend", "version": "1.0.0", "main": "src/index{ext}", "scripts": {{"dev": "nodemon src/index{ext}", "start": "node src/index{ext}"}}, "dependencies": {{"express": "^4.18.2", "cors": "^2.8.5", "dotenv": "^16.3.1"}}}}',
                f"src/index{ext}": f'const express = require("express");\nconst cors = require("cors");\n\nconst app = express();\napp.use(cors());\napp.use(express.json());\n\napp.get("/", (req, res) => res.json({{status: "running", app: "{project_name}"}}));\napp.get("/api/health", (req, res) => res.json({{status: "healthy"}}));\n\nconst PORT = process.env.PORT || 8000;\napp.listen(PORT, () => console.log(`Server running on port ${{PORT}}`));\n',
                ".env.example": f"PORT=8000\nDATABASE_URL=\nSECRET_KEY=your-secret-key\n",
            }
        elif bl == "go":
            project["backend"] = {
                "go.mod": f"module {project_name}\n\ngo 1.21\n",
                "main.go": 'package main\n\nimport (\n\t"fmt"\n\t"log"\n\t"net/http"\n)\n\nfunc main() {\n\thttp.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {\n\t\tfmt.Fprintf(w, `{"status":"running"}`)\n\t})\n\tlog.Println("Server on :8080")\n\tlog.Fatal(http.ListenAndServe(":8080", nil))\n}\n',
            }
        elif bl == "java":
            project["backend"] = {
                "pom.xml": f"<!-- {project_name} Maven config -->\n<project><!-- Spring Boot starter --></project>\n",
                "src/main/java/com/app/Application.java": 'package com.app;\n\nimport org.springframework.boot.SpringApplication;\nimport org.springframework.boot.autoconfigure.SpringBootApplication;\n\n@SpringBootApplication\npublic class Application {\n    public static void main(String[] args) {\n        SpringApplication.run(Application.class, args);\n    }\n}\n',
            }
        else:
            # Fallback to Python
            project["backend"] = {
                "main.py": BACKEND_MAIN.format(project_name=project_name),
                "requirements.txt": BACKEND_REQUIREMENTS,
            }
    
    # --- Frontend ---
    if frontend_fw and frontend_fw.lower() != "none":
        ff = detected.frontend_framework or frontend_fw
        
        if ff in ("Vue", "Vue.js"):
            project["frontend"] = {
                "package.json": f'{{"name": "{project_name}-frontend", "private": true, "version": "0.1.0", "type": "module", "scripts": {{"dev": "vite", "build": "vite build"}}, "dependencies": {{"vue": "^3.4.0"}}, "devDependencies": {{"@vitejs/plugin-vue": "^5.0.0", "vite": "^5.0.0"}}}}',
                "vite.config.js": "import { defineConfig } from 'vite'\nimport vue from '@vitejs/plugin-vue'\n\nexport default defineConfig({\n  plugins: [vue()],\n  server: { port: 3000, proxy: { '/api': 'http://localhost:8000' } }\n})\n",
                "index.html": FRONTEND_INDEX_HTML.format(project_name=project_name).replace('main.jsx', 'main.js'),
                "src": {
                    "main.js": "import { createApp } from 'vue'\nimport App from './App.vue'\nimport './style.css'\n\ncreateApp(App).mount('#app')\n",
                    "App.vue": f'<template>\n  <div class="app">\n    <h1>{project_name}</h1>\n    <p>Generated by VibeCoder</p>\n  </div>\n</template>\n\n<script setup>\n</script>\n\n<style scoped>\n.app {{ max-width: 800px; margin: 0 auto; padding: 2rem; }}\n</style>\n',
                    "style.css": FRONTEND_CSS,
                },
            }
        elif ff in ("Angular",):
            project["frontend"] = {
                "package.json": f'{{"name": "{project_name}-frontend", "version": "0.1.0", "scripts": {{"start": "ng serve", "build": "ng build"}}, "dependencies": {{"@angular/core": "^17.0.0"}}}}',
                "angular.json": "{}",
                "tsconfig.json": '{"compilerOptions": {"target": "ES2022", "module": "ES2022"}}',
                "src": {
                    "main.ts": "import { bootstrapApplication } from '@angular/platform-browser';\nimport { AppComponent } from './app/app.component';\n\nbootstrapApplication(AppComponent);\n",
                    "index.html": FRONTEND_INDEX_HTML.format(project_name=project_name),
                    "styles.css": FRONTEND_CSS,
                    "app": {
                        "app.component.ts": f"import {{ Component }} from '@angular/core';\n\n@Component({{selector: 'app-root', template: '<h1>{project_name}</h1>'}})\nexport class AppComponent {{}}\n",
                    },
                },
            }
        elif ff in ("Next.js", "Nextjs"):
            project["frontend"] = {
                "package.json": f'{{"name": "{project_name}-frontend", "version": "0.1.0", "scripts": {{"dev": "next dev", "build": "next build"}}, "dependencies": {{"next": "^14.0.0", "react": "^18.2.0", "react-dom": "^18.2.0"}}}}',
                "next.config.js": "/** @type {import('next').NextConfig} */\nconst nextConfig = {}\nmodule.exports = nextConfig\n",
                "app": {
                    "layout.tsx": f'export default function RootLayout({{ children }}: {{ children: React.ReactNode }}) {{\n  return <html><body>{{children}}</body></html>\n}}\n',
                    "page.tsx": f'export default function Home() {{\n  return <main><h1>{project_name}</h1><p>Generated by VibeCoder</p></main>\n}}\n',
                    "globals.css": FRONTEND_CSS,
                },
            }
        elif ff in ("Svelte", "SvelteKit"):
            project["frontend"] = {
                "package.json": f'{{"name": "{project_name}-frontend", "version": "0.1.0", "scripts": {{"dev": "vite dev", "build": "vite build"}}, "dependencies": {{}}, "devDependencies": {{"svelte": "^4.0.0", "@sveltejs/vite-plugin-svelte": "^3.0.0", "vite": "^5.0.0"}}}}',
                "svelte.config.js": "import adapter from '@sveltejs/adapter-auto';\n\nexport default { kit: { adapter: adapter() } };\n",
                "src": {
                    "routes": {
                        "+page.svelte": f'<h1>{project_name}</h1>\n<p>Generated by VibeCoder</p>\n',
                    },
                    "app.css": FRONTEND_CSS,
                },
            }
        else:
            # Default: React + Vite
            project["frontend"] = {
                "package.json": FRONTEND_PACKAGE_JSON.format(project_name=project_name),
                "vite.config.js": FRONTEND_VITE_CONFIG,
                "index.html": FRONTEND_INDEX_HTML.format(project_name=project_name),
                "src": {
                    "main.jsx": FRONTEND_MAIN_JSX,
                    "App.jsx": FRONTEND_APP_JSX.format(
                        project_name=project_name,
                        modules_list=modules_list
                    ),
                    "index.css": FRONTEND_CSS,
                }
            }
    
    # If nothing was generated, use the original React + FastAPI default
    if not project:
        project = {
            "backend": {
                "main.py": BACKEND_MAIN.format(project_name=project_name),
                "requirements.txt": BACKEND_REQUIREMENTS,
                ".env.example": BACKEND_ENV.format(project_name=project_name),
            },
            "frontend": {
                "package.json": FRONTEND_PACKAGE_JSON.format(project_name=project_name),
                "vite.config.js": FRONTEND_VITE_CONFIG,
                "index.html": FRONTEND_INDEX_HTML.format(project_name=project_name),
                "src": {
                    "main.jsx": FRONTEND_MAIN_JSX,
                    "App.jsx": FRONTEND_APP_JSX.format(
                        project_name=project_name,
                        modules_list=modules_list
                    ),
                    "index.css": FRONTEND_CSS,
                }
            },
        }
    
    # Always add README and .gitignore
    project["README.md"] = README_TEMPLATE.format(
        project_name=project_name,
        backend=backend_fw or architecture.get('backend', 'FastAPI'),
        frontend=frontend_fw or architecture.get('frontend', 'React'),
        database=architecture.get('database', 'PostgreSQL'),
        modules_md=modules_md
    )
    project[".gitignore"] = "node_modules/\n__pycache__/\n.env\n*.pyc\nvenv/\ndist/\n"
    
    return {project_name: project}
