/**
 * Mock Agent - For Testing
 * 
 * Validates the engine contract without real LLM calls.
 * DELETE after testing.
 */

import type { AgentEngine, AgentChange, WorkspaceContext } from "./types";

export class MockAgent implements AgentEngine {
    async generateChanges(_input: {
        prompt: string;
        context: WorkspaceContext;
        files: Record<string, string>;
    }): Promise<AgentChange[]> {
        // Simulate processing delay
        await new Promise((r) => setTimeout(r, 500));

        // Return deterministic output
        return [
            {
                path: "src/example.ts",
                content: `// Generated by MockAgent at ${new Date().toISOString()}
export const hello = "from mock agent";
`,
            },
        ];
    }
}

// Factory for testing
export function createMockEngine(): AgentEngine {
    return new MockAgent();
}
